const strings = {
  uz: {
    welcome: "Assalomu aleykum! Bu Alif Bank qo'llab-quvvatlash boti. Davom etish uchun tilni tanlang:",
    ask_atm: "Iltimos, terminal raqamini kiriting:",
    invalid_atm: "❌ Bunday raqamli bankomat topilmadi. Iltimos, raqamni tekshirib qaytadan kiriting:",
    ask_problem: "Iltimos, bankomatda yuzaga kelgan muammoni tasvirlab bering:",
    ask_amount: "Iltimos, bankomatga kiritilgan summani kiriting (so'm):",
    invalid_amount: "❌ Noto'g'ri summa. Iltimos, faqat raqam kiriting:",
    ask_card: "Iltimos, karta raqamingizning birinchi 4 raqamini kiriting:",
    invalid_card_first4: "❌ Noto'g'ri. Iltimos, faqat 4 ta raqam kiriting:",
    ask_card_last4: "Iltimos, karta raqamingizning oxirgi 4 raqamini kiriting:",
    invalid_card_last4: "❌ Noto'g'ri. Iltimos, faqat 4 ta raqam kiriting:",
    ask_phone: "Iltimos, pastdagi tugmani bosib telefon raqamingizni ulashing:",
    invalid_phone: "❌ To'g'ri telefon raqamini kiriting yoki kontaktni yuboring:",
    success: "Rahmat! Sizning arizangiz muvaffaqiyatli qabul qilindi. Tez orada siz bilan bog'lanamiz.",
  },
  ru: {
    welcome: "Ассалому алейкум! Это бот поддержки Алиф Банка. Выберите язык, чтобы продолжить:",
    ask_atm: "Пожалуйста, введите номер терминала:",
    invalid_atm: "❌ Терминал с таким номером не найден. Пожалуйста, проверьте номер и введите снова:",
    ask_problem: "Пожалуйста, опишите проблему, возникшую в терминале:",
    ask_amount: "Пожалуйста, введите сумму, внесенную в банкомат (сум):",
    invalid_amount: "❌ Неверная сумма. Пожалуйста, введите только число:",
    ask_card: "Пожалуйста, введите первые 4 цифры номера вашей карты:",
    invalid_card_first4: "❌ Неверно. Пожалуйста, введите ровно 4 цифры:",
    ask_card_last4: "Пожалуйста, введите последние 4 цифры номера вашей карты:",
    invalid_card_last4: "❌ Неверно. Пожалуйста, введите ровно 4 цифры:",
    ask_phone: "Пожалуйста, поделитесь своим номером телефона, нажав кнопку ниже:",
    invalid_phone: "❌ Введите корректный номер телефона или отправьте контакт:",
    success: "Спасибо! Ваша заявка успешно принята. Мы свяжемся с вами в ближайшее время.",
  },
  en: {
    welcome: "Assalomu aleykum! This is the Alif Bank support bot. Choose a language to continue:",
    ask_atm: "Please enter the terminal number:",
    invalid_atm: "❌ A terminal with this number was not found. Please check the number and re-enter:",
    ask_problem: "Please describe the problem that occurred with the terminal:",
    ask_amount: "Please enter the amount inserted into the ATM (UZS):",
    invalid_amount: "❌ Invalid amount. Please enter numbers only:",
    ask_card: "Please enter the first 4 digits of your card number:",
    invalid_card_first4: "❌ Invalid. Please enter exactly 4 digits:",
    ask_card_last4: "Please enter the last 4 digits of your card number:",
    invalid_card_last4: "❌ Invalid. Please enter exactly 4 digits:",
    ask_phone: "Please share your phone number by pressing the button below:",
    invalid_phone: "❌ Please enter a valid phone number or share your contact:",
    success: "Thank you! Your application has been successfully accepted. We will contact you soon.",
  }
};

module.exports = strings;