const strings = {
  uz: {
    welcome: "Assalomu aleykum! Bu Alif Bank qo'llab-quvvatlash boti. Davom etish uchun tilni tanlang:",
    ask_atm: "Iltimos, terminal raqamini kiriting:",
    ask_client: "Rahmat. Endi, iltimos, mijoz raqamingizni (ID) kiriting:",
    ask_phone: "Iltimos, pastdagi tugmani bosib telefon raqamingizni ulashing:",
    ask_problem: "Iltimos, bankomatda yuzaga kelgan muammoni tasvirlab bering:",
    success: "Rahmat! Sizning arizangiz muvaffaqiyatli qabul qilindi. Tez orada siz bilan bog'lanamiz.",
    invalid_atm: "❌ Bunday raqamli bankomat topilmadi. Iltimos, raqamni tekshirib qaytadan kiriting:",
    ask_card: "Rahmat. Endi, iltimos, bank karta raqamingizni kiriting:",
    invalid_card: "❌ Karta raqami noto'g'ri. Iltimos, 16 xonali raqamni boshqadan kiriting:",
    ask_amount: "Iltimos, bankomatga kiritilgan summani kiriting (so'm):",
    invalid_amount: "❌ Noto'g'ri summa. Iltimos, faqat raqam kiriting:",
    ask_time: "Iltimos, hodisa sodir bo'lgan sana va vaqtni kiriting (masalan: 22-iyul 14:30):",
  },
  ru: {
    welcome: "Ассалому алейкум! Это бот поддержки Алиф Банка. Выберите язык, чтобы продолжить:",
    ask_atm: "Пожалуйста, введите номер терминала:",
    ask_client: "Спасибо. Теперь, пожалуйста, введите ваш номер клиента (ID):",
    ask_phone: "Пожалуйста, поделитесь своим номером телефона, нажав кнопку ниже:",
    ask_problem: "Пожалуйста, опишите проблему, возникшую в терминале:",
    success: "Спасибо! Ваша заявка успешно принята. Мы свяжемся с вами в ближайшее время.",
    invalid_atm: "❌ Терминал с таким номером не найден. Пожалуйста, проверьте номер и введите снова:",
    ask_card: "Спасибо. Теперь, пожалуйста, введите номер вашей банковской карты:",
    invalid_card: "❌ Неверный номер карты. Пожалуйста, введите правильный 16-значный номер карты:",
    ask_amount: "Пожалуйста, введите сумму, внесенную в банкомат (сум):",
    invalid_amount: "❌ Неверная сумма. Пожалуйста, введите только число:",
    ask_time: "Пожалуйста, укажите дату и время происшествия (например: 22 июля 14:30):",
  },
  en: {
    welcome: "Assalomu aleykum! This is the Alif Bank support bot. Choose a language to continue:",
    ask_atm: "Please enter the terminal number:",
    ask_client: "Thank you. Now, please enter your client number (ID):",
    ask_phone: "Please share your phone number by pressing the button below:",
    ask_problem: "Please describe the problem that occurred with the terminal:",
    success: "Thank you! Your application has been successfully accepted. We will contact you soon.",
    invalid_atm: "❌ A terminal with this number was not found. Please check the number and re-enter:",
    ask_card: "Thank you. Now, please enter your bank card number:",
    invalid_card:"❌ Invalid card number. Please enter a valid 16-digit card number:",
    ask_amount: "Please enter the amount inserted into the ATM (UZS):",
    invalid_amount: "❌ Invalid amount. Please enter numbers only:",
    ask_time: "Please enter the date and time of the incident (e.g. July 22, 14:30):",
  }
};

module.exports = strings;
